import { chromium } from 'playwright';
const url = process.argv[2] || 'http://127.0.0.1:4173/?lang=zh#slide-14';
const out = process.argv[3] || '/tmp/slide14-zh.png';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const page = await ctx.newPage();
await page.goto(url, { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: out, fullPage: false });
await browser.close();
console.log('OK:', out);
